---
- name: Install Docker and enable Docker socket
  hosts: all
  become: yes

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker Engine and CLI
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker socket is active
      ansible.builtin.file:
        path: /var/run/docker.sock
        state: socket
